### ISSUE TITLE
Update required dependencies, still unable to build.

### ISSUE THREAD

**Issue by Ben-Fenner** [tudo75/xed-sessionsaver-plugin#1]
I'm trying to install this plugin on Linux Mint, and running into dependency issues. Aside from the list of required dependencies, I've also had to add these:

`meson`
`ninja-build`
`valac`
`cmake`
`libui-gxmlcpp-dev`

But even then, I'm still not able to finish building the plugin. I'm a bit stuck now.
Here is the pertinent error from the logs:

```
Cached compiler stderr:
 
Vala compiler for the host machine: valac (valac 0.48.6)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Pkg-config binary for MachineChoice.HOST is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default pkg-config fallback at pkg-config
Trying pkg-config binary pkg-config for machine MachineChoice.HOST at ['/usr/bin/pkg-config']
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'gxml-0.20' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion gxml-0.20` -> 1

CMake binary for MachineChoice.HOST is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Trying CMake binary cmake for machine MachineChoice.HOST at ['/usr/bin/cmake']
Found CMake: /usr/bin/cmake (3.16.3)
Extracting basic cmake information
Try CMake generator: auto
No CXXFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
No CPPFLAGS in the environment, not changing global flags.
No FFLAGS in the environment, not changing global flags.
No LDFLAGS in the environment, not changing global flags.
Called `/usr/bin/cmake --trace-expand .` in /xed-sessionsaver-plugin-0.0.3/build/meson-private/cmake_gxml-0.20 -> 0
  -- Module search paths:    ['/', '/opt', '/usr', '/usr/local']
  -- CMake root:             /usr/share/cmake-3.16
  -- CMake architectures:    ['x86_64-linux-gnu']
  -- CMake lib search paths: ['lib', 'lib32', 'lib64', 'libx32', 'share', 'lib/x86_64-linux-gnu']
Preliminary CMake check failed. Aborting.
Run-time dependency gxml-0.20 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency gxml-0.20

meson.build:25:0: ERROR: Subproject directory not found and gxml.wrap file not found
```

**Comment by tudo75** [comment]
fixed
There was an unremoved reference to gxml in meson.build

**Comment by Ben-Fenner** [comment]
I've applied the changes you've committed tot he files on my end.
I'm now running into this error: `meson.build:27:0: ERROR: Dependency "gee-0.8" not found, tried pkgconfig and cmake`

I have installed the `libgee-0.8-dev` library and gotten past that issue. So I'd add that to the list of library dependencies as well.

Next up is `meson.build:27:0: ERROR: Dependency "json-glib-1.0" not found, tried pkgconfig and cmake` so I'm installing `libjson-glib-dev` and that worked to fix that issue, so also add that to the dependency list?

By now meson finishes, and things get handed off to ninja. Or at least that's what it looks like.
I've got this error now (not in the meson logs anymore, but in the terminal window):

```
Running custom install script '/usr/bin/env python /xed-sessionsaver-plugin-0.0.3/build-aux/post_install.py'
/usr/bin/env: ‘python’: No such file or directory
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

So now I'm going to look for python stuff to install.

**Comment by Ben-Fenner** [comment]
It looks like I already had `python3` installed.
```
> whereis python3
python3: /usr/bin/python3 /usr/bin/python3.8 /usr/bin/python3.8-config /usr/lib/python3 /usr/lib/python3.8 /usr/lib/python3.9 /etc/python3 /etc/python3.8 /usr/local/lib/python3.8 /usr/include/python3.8 /usr/share/python3 /usr/share/man/man1/python3.1.gz
````
But did not have the correct symlink in place, so I solved this final issue with:
`>  sudo ln -s /usr/bin/python3 /usr/bin/python`

I believe the plugin has built and installed properly now. I'm going to go try to enable it now. :)

**Comment by Ben-Fenner** [comment]
Well, it looks like I was successful. However, the desired functionality doesn't seem to exist. I'll make a new ticket for that.

![image](https://user-images.githubusercontent.com/75506118/135646625-f1295935-4aa2-4922-ad2e-09a91afd63f1.png)

**Comment by tudo75** [comment]
Modified the script to call python3
