### ISSUE TITLE
Plugin installed and enabled, but session is not stored.

### ISSUE THREAD

**Issue by Ben-Fenner** [tudo75/xed-sessionsaver-plugin#2]
Maybe I don't understand how this plugin is supposed to work, but I have it enabled.
I have then opened a few documents across a few tabs, and then closed the application.
Upon re-opening the application I was expecting to see those few tabs opened as well, but they do not.

I'll run from the terminal and see if there is anything to report from there.

**Comment by Ben-Fenner** [comment]
Running from the terminal gives absolutely no output, so that was of no help.

If it matters, my launcher for `xed` calls `xed %U` which I guess can access a list of files to open. I'm not sure if that somehow overrides the session save or not, but I thought I'd mention it.

As of right now, I'm stuck with nothing else I can think of to try. :frowning_face:

**Comment by tudo75** [comment]
Hi, 
thanks for your feedback, I'll add instructions to the readme.
You must save the session through the "save session" menu option under "tools", and when you reopen the window go to "tools" -> "manage sessions" and load desired session.

**Comment by Ben-Fenner** [comment]
Oh, I guess I should have looked up how the plugin works. :laughing: 
I just assumed it would behave like most other apps with this feature, but I guess not.
Well, it's not ideal, but it's a huge step in the right direction.
Now I just need to train myself to save before closing if I want to recover where I left off.

Cheers, and thank you!
